# Ultra-minimal PTCC test - 2025-10-18 14:19
services:
  - type: web
    name: ptcc-demo
    env: python
    buildCommand: pip install -r requirements_ultra.txt
    startCommand: streamlit run main.py --server.port=$PORT --server.address=0.0.0.0
