# Minimal PTCC Deployment Test - 2025-10-18 14:16
services:
  - type: web
    name: ptcc-demo
    env: python
    buildCommand: pip install -r requirements_minimal.txt
    startCommand: streamlit run app_simple.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PORT
        value: 8501
